version: "3.9"

services:
  users-ms-api:
    container_name: users-ms-api
    build:
      context: ./
    depends_on:
      - "users-ms-pgdb"
      - "users-ms-redis"

  users-ms-pgdb:
    container_name: users-ms-pgdb
    image: postgres:latest
    ports:
    - "5432:5432"
    environment:
      POSTGRES_DB: "test"
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"

  users-ms-redis:
    container_name: users-ms-redis
    image: redis
    ports:
    - "6379:6379"
