version: "3.9"

services:
  users-ms-api:
    container_name: users-ms-api
    build:
      context: ./users-ms/
    ports:
    - "80:80"
    depends_on:
    - "users-ms-pgdb"

  users-ms-pgdb:
    container_name: users-ms-pgdb
    image: postgres:latest
    ports:
    - "5432:5432"
    environment:
      POSTGRES_DB: "test"
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
