version: '3.8'
services:
  transaction-ms:
    build:
      context: ./transaction-ms
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=credentials.json
      - GOOGLE_TOPIC_PATH=projects/dataarchitectures/topics/stock-transactions
    ports:
      - "5001:5000"